version: "3"

services:
  dynamodb_store:
    image: "amazon/dynamodb-local:latest"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
